### ISSUE TITLE
Division by 0 on front page

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms-module-imblogging#6]
In a new installation on impressCMS 2b1, on PHP8.0, I get a division by zero error in the icms_view_PageNav class. Commenting out line 84 in index.php makes it go away.

**Comment by skenow** [comment]
In index.php of imblogging? Line 84 is a blank line in the master branch

Maybe line 106 after the last merge for meta information?
`$pagenav = new icms_view_PageNav($posts_count, icms::$module->config['posts_limit'], $clean_start, 'start', $extr_arg);
`

**Comment by skenow** [comment]
What do you have for Posts Limit in the preferences for the module? The default is 5

**Comment by fiammybe** [comment]
Correct, it's line 106 now. I'll reinstall with the latest code, my personal branch looks to be outdated even though my IDE says not.

**Comment by skenow** [comment]
I haven't been able to reproduce this - even setting posts_limit to 0 or blank

**Comment by fiammybe** [comment]
The update to 1.2 RC fixes this problem. Closing.
